### PR TITLE
Julia DifferentialEquations applied

### PR DESCRIPTION
**Pull request by Stamp1993**
Replaced Sundials C-based code with julia DifferentialEquations interface, sundials implementations are not removed - just in case, runtestsWithModiaAndModia3D give the same errors and failures as your implemetations, simple runtests give one failure because of julia's smaller floating point precision, I'm going to fix it later. Logging is not implemented yet. I hope my implementation is a good addition to your project

### CODE REVIEW

**Comment by MartinOtter** [comment]
> Replaced Sundials C-based code with julia DifferentialEquations interface, 

Thanks. I plan to inspect this pull request in the next days.

> sundials implementations are not removed - just in case, runtestsWithModiaAndModia3D give the same errors and failures as your implemetations, simple runtests give one failure because of julia's smaller floating point precision, I'm going to fix it later. Logging is not implemented yet. I hope my implementation is a good addition to your project

Hm. Can you give more explanations:
- runtestsWithModiaAndModia3D was successful with latest ModiaMath, Modia, Modia3D. Which models do not run on your side (which versions of ModiaMath, Modia, Modia3D did you use)?
- What do you mean with Julias smaller floting point precision and what do yo plan to improve? Do my understanding, both Julia and C-Sundials use Float64.

**Comment by MartinOtter** [comment]
I tried a few examples with your pull request (e.g. ModiaMath/examples/Simulate_Pendulum.jl), but always get the following error after simulation started:
```
ERROR:` LoadError: BoundsError: attempt to access 0-element Array{Any,1} at index [0]

[...] ModiaMath\src\SimulationEngine\diffeq_simulate.jl:323  # this is: simModel.yp = sol.du[end]
```
Should any of the examples simulate?

**Comment by Stamp1993** [comment]
```
 ERROR:` LoadError: BoundsError: attempt to access 0-element Array{Any,1} at index [0]
 
 [...] ModiaMath\src\SimulationEngine\diffeq_simulate.jl:323  # this is: simModel.yp = sol.du[end]
```
Sorry, my fault, I've made some mistake with DASSL update, now it should be ok, so I'll update the dependencies and PR again

**Comment by Stamp1993** [comment]
> Hm. Can you give more explanations:
> 
> * runtestsWithModiaAndModia3D was successful with latest ModiaMath, Modia, Modia3D. Which models do not run on your side (which versions of ModiaMath, Modia, Modia3D did you use)?
ModiaMath 0.5.2-dev, Modia 0.3.0, Modia3D 0,3,0
> * What do you mean with Julias smaller floting point precision and what do you plan to improve? To my understanding, both Julia and C-Sundials use Float64.
C-Sundials uses Sundials.realtype which is 124-bit

**Pull request closed without merging**
