### PR TITLE
various fixes/updates for Julia v0.7

### PR DESCRIPTION
**Pull request by jrevels**
Drops Julia v0.6 support since supporting multiple language versions in a single codebase instance can be nightmarish.

Notes:

- There seems to be a bit of stylistic inconsistency across the codebase, so when making changes I either a) kept things locally consistent and/or b) tried to follow normal Julia style (e.g. https://docs.julialang.org/en/v1/manual/style-guide/index.html, though I'm not in full agreement with all of those conventions).

- I also ended up touching some of the code from https://github.com/ModiaSim/ModiaMath.jl/commit/479cec8d824db0dbc15ad6e9b2e09608c1b08e51, and basically reverted that commit with these changes. I'm not sure what problem it was trying to solve, but AFAICT, it is likely not the right solution; e.g. if the `Unitful` package loaded by `ModiaMath` is different than the `Unitful` package loaded at top-level in the same environment, then there's a deeper problem that needs solving.

- Deleted Project.toml/Manifest.toml. Package registration currently still uses the old REQUIRE/METADATA system, and [autogenerates the appropriate files for the new system](https://github.com/JuliaRegistries/General). AFAIK, it'll be easier if package developers wait for the "official" migration to the new Project.toml/Manifest.toml format rather than trying to preemptively migrate on their own.

I have a similar PR queued up for Modia, but let's tackle this first...

### CODE REVIEW

**Comment by jrevels** [comment]
I guess I would still need to update the README, assuming we can get CI passing

**Comment by MartinOtter** [comment]
> Drops Julia v0.6 support since supporting multiple language versions in a single codebase instance can be nightmarish.

Thanks for your pull request. The trouble is that Modia and Modia3D depend on ModiaMath and neither Modia nor Modia3D have been yet fully converted to Julia 0.7/1.0 and there might be still issues in ModiaMath that need to be fixed before Modia/Modia3D have been fully converted. **Furthermore, development is continuing in parallel**. Therefore, the strategy is to have one version of Modia/ModiaMath/Modia3D supporting Julia 0.6, 0.7, 1.0 and making releases of these versions (and accepting that the code is not nice at some places). After these releases, the support for Julia 0.6 and 0.7 is dropped and the development of all three packages continues only on the basis of Julia 1.0.

The most critical issue preventing currently to switch to Julia 1.0 is a [bug in Julia](https://github.com/JuliaLang/julia/issues/28917). Once this bug is fixed, switching to Julia 1.0 should be quick (a few days). 

To summarize, I need to wait with the acceptance of your pull request.


> Notes:
>
> -  There seems to be a bit of stylistic inconsistency across the codebase, so when making changes I either a) kept things locally consistent and/or b) tried to follow normal Julia style (e.g. https://docs.julialang.org/en/v1/manual/style-guide/index.html, though I'm not in full agreement with all of those conventions).

Thanks.

>
> - I also ended up touching some of the code from 479cec8, and basically reverted that commit with these changes. I'm not sure what problem it was trying to solve, but AFAICT, it is likely not the right solution; e.g. if the Unitful package loaded by ModiaMath is different than the Unitful package loaded at top-level in the same environment, then there's a deeper problem that needs solving.

I described the issue and the solution [here](https://discourse.julialang.org/t/travis-ci-fails-for-julia-v0-7-since-test-package-missing/13290/10?u=martinotter). I think this is a principal issue with the new package manager, but resolves this issue in a reasonable way (I like the new package manager **very much** and do not want to miss it again). If there are better solutions to this problem, this would be also fine for me. Note, "hoping" or "requiring" that a user has the right packages in his/her "environment" to execute examples and tests from the examples and test directories is not a stable solution (especially this assumption fails for example for Travis CL). With the approach in current ModiaMath, a user can execute an example (e.g. `import ModiaMath; include("$(ModiaMath.path)/examples/Simulate_Pendulum.jl"`) ) and this example will run successfully independent of the environment of the user because the only assumption is that "ModiaMath" must be in this environment.

> -    Deleted Project.toml/Manifest.toml. Package registration currently still uses the old REQUIRE/METADATA system, and autogenerates the appropriate files for the new system. AFAIK, it'll be easier if package developers wait for the "official" migration to the new Project.toml/Manifest.toml format rather than trying to preemptively migrate on their own.

Thanks for this information. I did not know this.

**Comment by tshort** [comment]
The code from [479cec8](https://github.com/ModiaSim/ModiaMath.jl/commit/479cec8d824db0dbc15ad6e9b2e09608c1b08e51) seems like a kludgy solution. I'm not sure what's the best approach. Maybe it points to the need for better Base tooling. 

How about including an `examples/Project.toml` with those dependencies? The user would have to activate that to run the code.

**Comment by MartinOtter** [comment]
> The code from 479cec8 seems like a kludgy solution. I'm not sure what's the best approach. Maybe it points to the need for better Base tooling.

Maybe it would be best to continue the discussion on discourse in the [original ticket](https://discourse.julialang.org/t/travis-ci-fails-for-julia-v0-7-since-test-package-missing/13290)

**Pull request closed without merging**
